version: 2
updates:
  # Enable version updates for pip dependencies
  - package-ecosystem: "pip"
    directory: "/cfb_data"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group minor and patch updates together to reduce PR noise
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Only allow security updates and minor/patch updates by default
    # Major updates will be created as separate PRs for manual review
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Also check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
