"""Pydantic models for game endpoints."""

from cfb_data.enums import Classification, MediaType, SeasonType

from .requests import (
    AdvancedBoxScoreRequest,
    CalendarRequest,
    GameMediaRequest,
    GamesRequest,
    GameWeatherRequest,
    PlayerGameStatsRequest,
    RecordsRequest,
    ScoreboardRequest,
    TeamGameStatsRequest,
)
from .responses import (
    AdvancedBoxScore,
    AdvancedGameInfo,
    AdvancedPlayerStats,
    AdvancedTeamStats,
    CalendarWeek,
    Game,
    GameMedia,
    GamePlayoff,
    GameStatus,
    GameWeather,
    PlayerGameStatCategory,
    PlayerGameStatPlayer,
    PlayerGameStats,
    PlayerGameStatsTeam,
    PlayerGameStatType,
    PlayerGameUsage,
    PlayerPPA,
    PlayerStatsByQuarter,
    ScoreboardBetting,
    ScoreboardGame,
    ScoreboardTeam,
    ScoreboardVenue,
    ScoreboardWeather,
    StatsByQuarter,
    TeamExplosiveness,
    TeamFieldPosition,
    TeamGameStat,
    TeamGameStats,
    TeamGameStatsTeam,
    TeamHavoc,
    TeamPPA,
    TeamRecord,
    TeamRecords,
    TeamRushingStats,
    TeamScoringOpportunities,
    TeamSuccessRates,
)

__all__ = [
    # Request models
    "GamesRequest",
    "CalendarRequest",
    "RecordsRequest",
    "ScoreboardRequest",
    "GameMediaRequest",
    "GameWeatherRequest",
    "PlayerGameStatsRequest",
    "TeamGameStatsRequest",
    "AdvancedBoxScoreRequest",
    # Response models
    "SeasonType",
    "Classification",
    "MediaType",
    "GameStatus",
    "GamePlayoff",
    "Game",
    "CalendarWeek",
    "GameMedia",
    "GameWeather",
    "TeamRecord",
    "TeamRecords",
    "ScoreboardVenue",
    "ScoreboardTeam",
    "ScoreboardWeather",
    "ScoreboardBetting",
    "ScoreboardGame",
    "PlayerGameStatPlayer",
    "PlayerGameStatType",
    "PlayerGameStatCategory",
    "PlayerGameStatsTeam",
    "PlayerGameStats",
    "TeamGameStat",
    "TeamGameStatsTeam",
    "TeamGameStats",
    "StatsByQuarter",
    "TeamPPA",
    "TeamSuccessRates",
    "TeamExplosiveness",
    "TeamRushingStats",
    "TeamHavoc",
    "TeamScoringOpportunities",
    "TeamFieldPosition",
    "PlayerStatsByQuarter",
    "PlayerGameUsage",
    "PlayerPPA",
    "AdvancedGameInfo",
    "AdvancedTeamStats",
    "AdvancedPlayerStats",
    "AdvancedBoxScore",
]
