repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 25.1.0        # Use a fixed tag or commit SHA
    hooks:
      - id: black

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.7
    hooks:
      - id: sphinx-lint

  - repo: https://github.com/econchick/interrogate
    rev: 1.6.0
    additional_dependencies:
      - setuptools
    hooks:
      - id: interrogate
        args: [--fail-under=100, --verbose]
