"""Export the supported Coaches namespace and public contracts."""

from .models.pydantic import (
    Coach,
    CoachAlmaMater,
    CoachCareer,
    CoachCfpContext,
    CoachCfpOutcome,
    CoachDraftContext,
    CoachesRequest,
    CoachPollResume,
    CoachProfile,
    CoachProfileRequest,
    CoachRatingContext,
    CoachRecord,
    CoachRecordSplits,
    CoachRecruitingContext,
    CoachReference,
    CoachScoring,
    CoachSeason,
    CoachSeasonsRequest,
    CoachSeasonTeamReference,
    CoachTeamReference,
    CoachTenure,
    CoachTenuresRequest,
    CoachYearOverYear,
    DetailedCoachSeason,
)
from .resource import CoachesResource

__all__ = [
    "Coach",
    "CoachAlmaMater",
    "CoachCareer",
    "CoachCfpContext",
    "CoachCfpOutcome",
    "CoachDraftContext",
    "CoachesRequest",
    "CoachesResource",
    "CoachPollResume",
    "CoachProfile",
    "CoachProfileRequest",
    "CoachRatingContext",
    "CoachRecord",
    "CoachRecordSplits",
    "CoachRecruitingContext",
    "CoachReference",
    "CoachScoring",
    "CoachSeason",
    "CoachSeasonsRequest",
    "CoachSeasonTeamReference",
    "CoachTeamReference",
    "CoachTenure",
    "CoachTenuresRequest",
    "CoachYearOverYear",
    "DetailedCoachSeason",
]
