"""Access validated CollegeFootballData endpoints as pandas or Polars frames."""

from .adjusted_metrics.models.pydantic.requests import (
    AdjustedPlayerPassingRequest,
    AdjustedPlayerRushingRequest,
    AdjustedTeamMetricsRequest,
    KickerPAARRequest,
)
from .betting.models.pydantic.requests import BettingLinesRequest
from .cache import (
    CacheConfig,
    CacheMode,
    CachePolicyConfig,
    CacheProfile,
    CacheTTL,
    RedisCacheConfig,
    SQLiteCacheConfig,
)
from .client import CFBDClient, DataFrameBackend
from .coaches.models.pydantic.requests import (
    CoachesRequest,
    CoachProfileRequest,
    CoachSeasonsRequest,
    CoachTenuresRequest,
)
from .conferences.models.pydantic.requests import (
    ConferenceAffiliationsRequest,
    ConferenceChangesRequest,
    ConferencesRequest,
)
from .conferences.models.pydantic.responses import ConferenceClassification
from .draft.models.pydantic.requests import DraftPicksRequest
from .drives.models.pydantic.requests import DrivesRequest
from .enums import (
    Classification,
    MediaType,
    PlayoffCompetition,
    PlayoffRound,
    RankingPoll,
    RecruitClassification,
    SeasonType,
    TransferEligibility,
    UserUsageApi,
)
from .errors import (
    CFBDAuthenticationError,
    CFBDAuthorizationError,
    CFBDCacheBackendError,
    CFBDCacheError,
    CFBDCacheMissError,
    CFBDClientStateError,
    CFBDConfigurationError,
    CFBDDataFrameConversionError,
    CFBDError,
    CFBDHTTPError,
    CFBDIdentityAmbiguityError,
    CFBDIdentityNotFoundError,
    CFBDOptionalDependencyError,
    CFBDRateLimitError,
    CFBDRequestValidationError,
    CFBDResponseDecodeError,
    CFBDResponseValidationError,
    CFBDServerError,
    CFBDTimeoutError,
    CFBDTLSError,
    CFBDTransportError,
)
from .games.models.pydantic.requests import (
    AdvancedBoxScoreRequest,
    CalendarRequest,
    GameMediaRequest,
    GamesRequest,
    GameWeatherRequest,
    PlayerGameStatsRequest,
    RecordsRequest,
    ScoreboardRequest,
    TeamGameStatsRequest,
)
from .games.models.pydantic.responses import AdvancedBoxScore
from .identities import (
    AthleteIdentity,
    ConferenceIdentity,
    FreshnessMode,
    GameIdentity,
    HydrationPlan,
    TeamIdentity,
    VenueIdentity,
)
from .info.models.pydantic.requests import InfoUsageRequest
from .info.models.pydantic.responses import UserInfo, UserUsage
from .metrics.models.pydantic.requests import (
    PlayerGamePPARequest,
    PlayerSeasonPPARequest,
    PredictedPointsRequest,
    PregameWinProbabilityRequest,
    TeamGamePPARequest,
    TeamSeasonPPARequest,
    WinProbabilityRequest,
)
from .players.models.pydantic.requests import (
    PlayerSearchRequest,
    PlayerSeasonOverviewRequest,
    PlayerUsageRequest,
    ReturningProductionRequest,
    TransferPortalRequest,
)
from .playoffs.models.pydantic.requests import (
    CfpGamesRequest,
    CfpParticipantsRequest,
    CfpPlayoffRequest,
)
from .playoffs.models.pydantic.responses import CfpPlayoff
from .plays.models.pydantic.requests import (
    LivePlaysRequest,
    PlaysRequest,
    PlayStatsRequest,
)
from .plays.models.pydantic.responses import DownType, HomeAway, LiveGame, RushPass
from .rankings.models.pydantic.requests import RankingsRequest
from .ratings.models.pydantic.requests import (
    ConferenceSPRatingsRequest,
    CoreRatingsRequest,
    EloRatingsRequest,
    ExpandedSRSRatingsRequest,
    FPIRatingsRequest,
    SPRatingsRequest,
    SRSRatingsRequest,
)
from .recruiting.models.pydantic.requests import (
    RecruitingGroupsRequest,
    RecruitingPlayersRequest,
    RecruitingTeamsRequest,
)
from .retry import RetryPolicy
from .stats.models.pydantic.requests import (
    AdvancedGameStatsRequest,
    AdvancedSeasonStatsRequest,
    GameHavocRequest,
    PlayerGameSuccessRequest,
    PlayerSeasonStatsRequest,
    PlayerSeasonSuccessRequest,
    TeamSeasonStatsRequest,
)
from .teams.models.pydantic.requests import (
    FBSTeamsRequest,
    RosterRequest,
    TalentRequest,
    TeamATSRequest,
    TeamMatchupRequest,
    TeamsRequest,
)

__all__ = [
    "AdjustedPlayerPassingRequest",
    "AdjustedPlayerRushingRequest",
    "AdjustedTeamMetricsRequest",
    "AthleteIdentity",
    "AdvancedBoxScoreRequest",
    "AdvancedBoxScore",
    "AdvancedGameStatsRequest",
    "AdvancedSeasonStatsRequest",
    "BettingLinesRequest",
    "CalendarRequest",
    "CacheConfig",
    "CacheMode",
    "CachePolicyConfig",
    "CacheProfile",
    "CacheTTL",
    "CfpGamesRequest",
    "CfpParticipantsRequest",
    "CfpPlayoff",
    "CfpPlayoffRequest",
    "CFBDAuthenticationError",
    "CFBDAuthorizationError",
    "CFBDCacheBackendError",
    "CFBDCacheError",
    "CFBDCacheMissError",
    "CFBDClient",
    "CFBDClientStateError",
    "CFBDConfigurationError",
    "CFBDDataFrameConversionError",
    "CFBDError",
    "CFBDHTTPError",
    "CFBDIdentityAmbiguityError",
    "CFBDIdentityNotFoundError",
    "CFBDOptionalDependencyError",
    "CFBDRateLimitError",
    "CFBDRequestValidationError",
    "CFBDResponseDecodeError",
    "CFBDResponseValidationError",
    "CFBDServerError",
    "CFBDTimeoutError",
    "CFBDTLSError",
    "CFBDTransportError",
    "Classification",
    "CoachesRequest",
    "CoachProfileRequest",
    "CoachSeasonsRequest",
    "CoachTenuresRequest",
    "ConferenceAffiliationsRequest",
    "ConferenceChangesRequest",
    "ConferenceClassification",
    "ConferenceIdentity",
    "ConferencesRequest",
    "ConferenceSPRatingsRequest",
    "CoreRatingsRequest",
    "DataFrameBackend",
    "DraftPicksRequest",
    "DrivesRequest",
    "EloRatingsRequest",
    "ExpandedSRSRatingsRequest",
    "FPIRatingsRequest",
    "FreshnessMode",
    "GameMediaRequest",
    "GameIdentity",
    "GamesRequest",
    "GameWeatherRequest",
    "GameHavocRequest",
    "FBSTeamsRequest",
    "HomeAway",
    "HydrationPlan",
    "InfoUsageRequest",
    "KickerPAARRequest",
    "LiveGame",
    "LivePlaysRequest",
    "MediaType",
    "PlayerGameStatsRequest",
    "PlayerGamePPARequest",
    "PlayerGameSuccessRequest",
    "PlayoffCompetition",
    "PlayoffRound",
    "PlaysRequest",
    "PlayStatsRequest",
    "PlayerSeasonStatsRequest",
    "PlayerSearchRequest",
    "PlayerSeasonOverviewRequest",
    "PlayerSeasonPPARequest",
    "PlayerSeasonSuccessRequest",
    "PlayerUsageRequest",
    "PredictedPointsRequest",
    "PregameWinProbabilityRequest",
    "RecordsRequest",
    "RankingPoll",
    "RankingsRequest",
    "RecruitClassification",
    "RecruitingGroupsRequest",
    "RecruitingPlayersRequest",
    "RecruitingTeamsRequest",
    "RedisCacheConfig",
    "RetryPolicy",
    "RosterRequest",
    "ReturningProductionRequest",
    "RushPass",
    "ScoreboardRequest",
    "SeasonType",
    "SPRatingsRequest",
    "SRSRatingsRequest",
    "SQLiteCacheConfig",
    "TeamGamePPARequest",
    "TeamIdentity",
    "TeamGameStatsRequest",
    "TeamSeasonStatsRequest",
    "TeamSeasonPPARequest",
    "TalentRequest",
    "TeamATSRequest",
    "TeamMatchupRequest",
    "TeamsRequest",
    "TransferPortalRequest",
    "TransferEligibility",
    "UserInfo",
    "UserUsage",
    "UserUsageApi",
    "VenueIdentity",
    "WinProbabilityRequest",
    "DownType",
]
