"""Author modular, composable, and durably executable analytics recipes."""

from ._recipes import (
    DatasetRecipe,
    SourceRecipe,
    StepRecipe,
    WorkflowRecipe,
    dataset,
    source,
    step,
    workflow,
)
from .config import AnalyticsConfig, RecipeProviderTrust
from .discovery import RecipeSnapshot, discover_recipes
from .errors import (
    CFBDAnalyticsError,
    CFBDArtifactCodecError,
    CFBDArtifactCorruptionError,
    CFBDArtifactError,
    CFBDAttemptBudgetExceeded,
    CFBDExecutorError,
    CFBDPersistenceError,
    CFBDRecipeCompilationError,
    CFBDRecipeConfigurationError,
    CFBDRecipeDiscoveryError,
    CFBDRecipeParameterError,
    CFBDRecipeUsageError,
    CFBDRunError,
    CFBDTransformError,
)
from .observability import (
    AnalyticsEvent,
    AnalyticsEventType,
    AnalyticsObserver,
    AnalyticsOutcome,
    AnalyticsStats,
    AnalyticsStatsSnapshot,
)
from .operations import (
    NestedTransformDiagnostics,
    NestedTransformResult,
    explode_list,
    flatten_struct,
    nested_value,
    require_one,
    value,
)
from .planning import ExecutionPolicy, RecipeInspection, RecipePlan, RecipePlanNode
from .results import (
    ArtifactDescriptor,
    ArtifactRef,
    RecipeRun,
    RunNodeEvidence,
    WorkflowOutputs,
)
from .tabular import (
    PortableDType,
    rename_columns,
    select_columns,
    sort_rows,
    strict_cast_columns,
)
from .types import RecipeRef, SourceContext, ValueRef

__all__ = [
    "AnalyticsConfig",
    "AnalyticsEvent",
    "AnalyticsEventType",
    "AnalyticsObserver",
    "AnalyticsOutcome",
    "AnalyticsStats",
    "AnalyticsStatsSnapshot",
    "ArtifactDescriptor",
    "ArtifactRef",
    "CFBDAnalyticsError",
    "CFBDArtifactCodecError",
    "CFBDArtifactCorruptionError",
    "CFBDArtifactError",
    "CFBDPersistenceError",
    "CFBDAttemptBudgetExceeded",
    "CFBDExecutorError",
    "CFBDTransformError",
    "CFBDRecipeCompilationError",
    "CFBDRecipeConfigurationError",
    "CFBDRecipeDiscoveryError",
    "CFBDRecipeParameterError",
    "CFBDRecipeUsageError",
    "CFBDRunError",
    "DatasetRecipe",
    "ExecutionPolicy",
    "RecipeRef",
    "RecipeProviderTrust",
    "RecipeRun",
    "RecipeInspection",
    "RecipePlan",
    "RecipePlanNode",
    "RecipeSnapshot",
    "SourceContext",
    "SourceRecipe",
    "StepRecipe",
    "ValueRef",
    "RunNodeEvidence",
    "WorkflowOutputs",
    "WorkflowRecipe",
    "dataset",
    "discover_recipes",
    "explode_list",
    "flatten_struct",
    "nested_value",
    "NestedTransformDiagnostics",
    "NestedTransformResult",
    "PortableDType",
    "rename_columns",
    "select_columns",
    "source",
    "sort_rows",
    "step",
    "strict_cast_columns",
    "workflow",
    "require_one",
    "value",
]
