"""Pydantic models for game endpoints."""

from .requests import (
    GamesRequest,
    CalendarRequest,
    RecordsRequest,
    GameMediaRequest,
    GameWeatherRequest,
    PlayerGameStatsRequest,
    TeamGameStatsRequest,
    AdvancedBoxScoreRequest,
)
from .responses import (
    SeasonType,
    Division,
    MediaType,
    TeamInfo,
    Venue,
    Game,
    CalendarWeek,
    GameMedia,
    GameWeather,
    TeamRecord,
    TeamRecords,
    PlayerGamePassing,
    PlayerGameRushing,
    PlayerGameReceiving,
    PlayerGameDefensive,
    PlayerGameStats,
    TeamGameStats,
    BoxScoreTeamStats,
    BoxScorePlayerUsage,
    BoxScorePlayerPPA,
    AdvancedBoxScore,
    GameLine,
    Scoreboard,
)

__all__ = [
    # Request models
    "GamesRequest",
    "CalendarRequest",
    "RecordsRequest",
    "GameMediaRequest",
    "GameWeatherRequest",
    "PlayerGameStatsRequest",
    "TeamGameStatsRequest",
    "AdvancedBoxScoreRequest",
    # Response models
    "SeasonType",
    "Division",
    "MediaType",
    "TeamInfo",
    "Venue",
    "Game",
    "CalendarWeek",
    "GameMedia",
    "GameWeather",
    "TeamRecord",
    "TeamRecords",
    "PlayerGamePassing",
    "PlayerGameRushing",
    "PlayerGameReceiving",
    "PlayerGameDefensive",
    "PlayerGameStats",
    "TeamGameStats",
    "BoxScoreTeamStats",
    "BoxScorePlayerUsage",
    "BoxScorePlayerPPA",
    "AdvancedBoxScore",
    "GameLine",
    "Scoreboard",
]
