"""Export the supported Stats namespace and public contracts."""

from cfb_data.enums import Classification, SeasonType

from .models.pydantic import (
    AdvancedGameDefense,
    AdvancedGameOffense,
    AdvancedGameStat,
    AdvancedGameStatsRequest,
    AdvancedSeasonDefense,
    AdvancedSeasonOffense,
    AdvancedSeasonStat,
    AdvancedSeasonStatsRequest,
    FieldPosition,
    GameDownStats,
    GameHavocRequest,
    GameHavocStats,
    GameHavocUnit,
    GamePlayStats,
    Havoc,
    PlayerGameSuccessRate,
    PlayerGameSuccessRequest,
    PlayerSeasonStatsRequest,
    PlayerSeasonSuccessRate,
    PlayerSeasonSuccessRequest,
    PlayerStat,
    PlayerSuccessRateSplit,
    SeasonDownStats,
    SeasonPassingDownStats,
    SeasonPlayStats,
    StatCategory,
    TeamSeasonStatsRequest,
    TeamStat,
)
from .resource import StatsResource

__all__ = [
    "AdvancedGameDefense",
    "AdvancedGameOffense",
    "AdvancedGameStat",
    "AdvancedGameStatsRequest",
    "AdvancedSeasonDefense",
    "AdvancedSeasonOffense",
    "AdvancedSeasonStat",
    "AdvancedSeasonStatsRequest",
    "Classification",
    "FieldPosition",
    "GameDownStats",
    "GameHavocRequest",
    "GameHavocStats",
    "GameHavocUnit",
    "GamePlayStats",
    "Havoc",
    "PlayerGameSuccessRate",
    "PlayerGameSuccessRequest",
    "PlayerSeasonStatsRequest",
    "PlayerSeasonSuccessRate",
    "PlayerSeasonSuccessRequest",
    "PlayerStat",
    "PlayerSuccessRateSplit",
    "SeasonDownStats",
    "SeasonPassingDownStats",
    "SeasonPlayStats",
    "SeasonType",
    "StatCategory",
    "StatsResource",
    "TeamSeasonStatsRequest",
    "TeamStat",
]
