"""Generate user-facing team and conference enums from live CFBD data."""

from __future__ import annotations

import argparse
import asyncio
import json
import keyword
import re
import unicodedata
from collections.abc import Iterable, Sequence
from pathlib import Path

from cfb_data import CFBDClient

_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
_OUTPUT_PATH = _REPOSITORY_ROOT / "cfb_data" / "cfb_data" / "_reference_enums.py"


def _member_name(value: str, *, uppercase: bool, prefix: str) -> str:
    """Return a deterministic Python identifier for an upstream display value."""
    ascii_value = (
        unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    )
    joined_words = ascii_value.replace("'", "").replace("’", "").replace("&", "")
    words = re.findall(r"[A-Za-z0-9]+", joined_words)
    if not words:
        raise ValueError(f"Cannot derive an enum member from {value!r}")

    if uppercase:
        member = "".join(words).upper()
    else:
        member = "".join(
            word if word.isupper() else f"{word[:1].upper()}{word[1:]}"
            for word in words
        )

    if member[0].isdigit():
        member = f"{prefix}{member}"
    if keyword.iskeyword(member):
        member = f"{member}_"
    if not member.isidentifier():
        raise ValueError(f"Generated invalid enum member {member!r} from {value!r}")
    return member


def _validated_names(values: Iterable[object], *, source: str) -> tuple[str, ...]:
    """Return sorted, unique, non-empty names from one validated frame column."""
    names: list[str] = []
    for value in values:
        if not isinstance(value, str) or not value or value != value.strip():
            raise ValueError(f"{source} returned an invalid display value: {value!r}")
        names.append(value)

    if not names:
        raise ValueError(f"{source} returned no display values")
    if len(names) != len(set(names)):
        raise ValueError(f"{source} returned duplicate display values")
    return tuple(sorted(names))


def _enum_members(
    values: Sequence[str], *, uppercase: bool, prefix: str
) -> tuple[tuple[str, str], ...]:
    """Pair source values with unique deterministic enum member names."""
    members: list[tuple[str, str]] = []
    seen: dict[str, str] = {}
    for value in values:
        member = _member_name(value, uppercase=uppercase, prefix=prefix)
        if member in seen:
            raise ValueError(
                f"Enum member collision for {member!r}: {seen[member]!r} and {value!r}"
            )
        seen[member] = value
        members.append((member, value))
    return tuple(members)


async def _fetch_names(year: int) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Fetch team and conference names returned for one season."""
    async with CFBDClient() as client:
        team_frame = await client.teams.list(year=year)
        conference_frame = await client.conferences.list(year=year)

    team_names = _validated_names(
        team_frame["school"].tolist(),
        source=f"GET /teams?year={year}",
    )
    conference_names = _validated_names(
        conference_frame["name"].tolist(),
        source=f"GET /conferences?year={year}",
    )
    return team_names, conference_names


def _render_enum(
    class_name: str,
    docstring: str,
    members: Sequence[tuple[str, str]],
) -> list[str]:
    """Render one explicit ``StrEnum`` class for static-analysis discovery."""
    lines = [f"class {class_name}(StrEnum):", f'    """{docstring}"""', ""]
    lines.extend(
        f"    {member} = {json.dumps(value, ensure_ascii=False)}"
        for member, value in members
    )
    return lines


def _render_module(
    *,
    year: int,
    teams: Sequence[tuple[str, str]],
    conferences: Sequence[tuple[str, str]],
) -> str:
    """Render the complete generated reference-enum module."""
    lines = [
        '"""Define live-source CFBD team and conference names.',
        "",
        "Generated by ``scripts/generate_reference_enums.py`` from authenticated",
        f"``GET /teams?year={year}`` and ``GET /conferences?year={year}`` calls.",
        "Do not edit this module by hand.",
        '"""',
        "",
        "from enum import StrEnum",
        "from typing import Final",
        "",
        f"REFERENCE_SEASON: Final[int] = {year}",
        "",
        "",
    ]
    lines.extend(
        _render_enum(
            "TeamName",
            f"Identify a team returned in CFBD's {year} season reference data.",
            teams,
        )
    )
    lines.extend(["", ""])
    lines.extend(
        _render_enum(
            "ConferenceName",
            f"Identify a conference returned in CFBD's {year} season reference data.",
            conferences,
        )
    )
    lines.extend(
        [
            "",
            "",
            "teams: Final[type[TeamName]] = TeamName",
            "conferences: Final[type[ConferenceName]] = ConferenceName",
            "",
            "__all__ = [",
            '    "ConferenceName",',
            '    "REFERENCE_SEASON",',
            '    "TeamName",',
            '    "conferences",',
            '    "teams",',
            "]",
            "",
        ]
    )
    return "\n".join(lines)


def _parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--year",
        type=int,
        required=True,
        help="Season whose returned teams and conferences should be generated.",
    )
    return parser


async def _generate(year: int) -> tuple[int, int]:
    """Fetch live values and atomically replace the generated module."""
    team_names, conference_names = await _fetch_names(year)
    team_members = _enum_members(team_names, uppercase=False, prefix="Team")
    conference_members = _enum_members(
        conference_names,
        uppercase=True,
        prefix="Conference",
    )
    rendered = _render_module(
        year=year,
        teams=team_members,
        conferences=conference_members,
    )
    temporary_path = _OUTPUT_PATH.with_suffix(".py.tmp")
    temporary_path.write_text(rendered, encoding="utf-8")
    temporary_path.replace(_OUTPUT_PATH)
    return len(team_members), len(conference_members)


def main() -> None:
    """Generate the checked-in enums from authenticated live API calls."""
    arguments = _parser().parse_args()
    team_count, conference_count = asyncio.run(_generate(arguments.year))
    print(
        f"Generated {team_count} teams and {conference_count} conferences "
        f"for {arguments.year} in {_OUTPUT_PATH}"
    )


if __name__ == "__main__":
    main()
