"""Export the supported Ratings namespace and public contracts."""

from cfb_data.enums import Classification, SeasonType

from .models.pydantic import (
    ConferenceSP,
    ConferenceSPDefense,
    ConferenceSPOffense,
    ConferenceSPRatingsRequest,
    CoreRatingSeasonType,
    CoreRatingsRequest,
    EloRatingsRequest,
    ExpandedSRSRatingsRequest,
    ExpandedTeamSRS,
    FPIEfficiencies,
    FPIRatingsRequest,
    FPIResumeRanks,
    SPDefense,
    SPHavoc,
    SPOffense,
    SPRatingsRequest,
    SPSpecialTeams,
    SRSRatingsRequest,
    TeamCoreRating,
    TeamElo,
    TeamFPI,
    TeamSP,
    TeamSRS,
)
from .resource import RatingsResource

__all__ = [
    "Classification",
    "ConferenceSP",
    "ConferenceSPDefense",
    "ConferenceSPOffense",
    "ConferenceSPRatingsRequest",
    "CoreRatingSeasonType",
    "CoreRatingsRequest",
    "EloRatingsRequest",
    "ExpandedSRSRatingsRequest",
    "ExpandedTeamSRS",
    "FPIEfficiencies",
    "FPIResumeRanks",
    "FPIRatingsRequest",
    "RatingsResource",
    "SPDefense",
    "SPHavoc",
    "SPOffense",
    "SPRatingsRequest",
    "SPSpecialTeams",
    "SRSRatingsRequest",
    "SeasonType",
    "TeamCoreRating",
    "TeamElo",
    "TeamFPI",
    "TeamSP",
    "TeamSRS",
]
