name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.x"

      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('cfb_data/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache pre-commit environments
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Create & activate virtualenv, install deps
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install --upgrade pip
          pip install -r cfb_data/requirements.txt pre-commit pytest

      - name: Install pre-commit hooks
        run: |
          source .env/bin/activate
          pre-commit install --install-hooks

      - name: Run pre-commit on changed files
        run: |
          source .env/bin/activate
          # Fetch the target branch to compare against
          git fetch origin main
          # List changed files in this PR
          files=$(git diff --name-only origin/main...HEAD)
          # Filter to files tracked by pre-commit (e.g. .py, .md, etc.)
          changed=$(echo "$files" | grep -E '\.py$|\.md$|\.yaml$' || true)
          if [ -n "$changed" ]; then
            echo "Linting changed files:"
            echo "$changed"
            pre-commit run --files $changed
          else
            echo "No relevant files changed; skipping pre-commit."
          fi

      - name: Run tests
        run: |
          source .env/bin/activate
          pytest -q
